export const foodData = [
  {
    name: "Vadapav",
    description: "Something",
    id: "f1",
    price: "15",
    category: "breakfast",
    url: "https://www.cookwithmanali.com/wp-content/uploads/2018/04/Vada-Pav-500x375.jpg",
  },
  {
    name: "Chai",
    description: "Something",
    id: "f2",
    price: "10",
    url: "https://cdn2.foodviva.com/static-content/food-images/tea-recipes/milk-tea-recipe/milk-tea-recipe.jpg",
  },
  {
    name: "idali-dosa",
    description: "Something",
    id: "f3",
    price: "50",
    category: "breakfast",
    url: "https://1.bp.blogspot.com/-bAr7TPvKLs8/XINpM6F844I/AAAAAAAA6s4/FVEgfbgRlVcJOVxnUjWK9tAKcmUYxLVUwCLcBGAs/s1600/ration-rice-idli.jpg",
  },
  {
    name: "Misal-pav",
    description: "Something",
    id: "f4",
    price: "70",
    url: "https://myfoodstory.com/wp-content/uploads/2022/01/Misal-Pav-1.jpg",
  },
  {
    name: "Veg Thali",
    description: "Something",
    id: "f5",
    price: "150",
    category: "lunch",
    url: "https://eastindianrecipes.net/wp-content/uploads/2022/09/How-to-Make-North-Indian-Thali-Vegetarian-7-500x500.jpg",
  },
  {
    name: "Biryani",
    description: "Something",
    id: "f6",
    category: "lunch",
    price: "300",
    url: "https://www.licious.in/blog/wp-content/uploads/2020/12/Hyderabadi-chicken-Biryani.jpg",
  },
  {
    name: "Chinease",
    description: "Something",
    id: "f7",
    category: "lunch",
    price: "200",
    url: "https://content.jdmagicbox.com/comp/mumbai/c9/022pxx22.xx22.200222070907.d7c9/catalogue/hot-box-chinese-food-jogeshwari-west-mumbai-fast-food-fxaljns2ox.jpg",
  },
  {
    name: "Poha",
    description: "Something",
    id: "f8",
    category: "breakfast",
    price: "50",
    url: "https://www.indianveggiedelight.com/wp-content/uploads/2022/07/poha-recipe-featured.jpg",
  },
  {
    name: "Egg Bhuraji",
    description: "Something",
    id: "f9",
    category: "breakfast",
    price: "70",
    url: "https://www.ruchifoodline.com/recipes//cdn/recipes/Egg-Bhurji-1-3.jpg",
  },
  {
    name: "Paratha",
    description: "Something",
    id: "f10",
    category: "breakfast",
    price: "100",
    url: "https://arpitasfoodpod.com/wp-content/uploads/2021/06/8B21D1CF-A4EC-4B5F-B70E-FA56927CF4B0.jpeg",
  },
  {
    name: "Dal Makhani",
    description: "Something",
    id: "f11",
    category: "lunch",
    price: "250",
    url: "https://www.funfoodfrolic.com/wp-content/uploads/2023/04/Dal-Makhani-Blog.jpg",
  },
  {
    name: "Aloo Gobi",
    description: "Something",
    id: "f12",
    category: "lunch",
    price: "220",
    url: "https://ministryofcurry.com/wp-content/uploads/2017/04/Aloo-Gobi-5.jpg",
  },
  {
    name: "Mattar Panner",
    description: "Something",
    id: "f13",
    category: "dinner",
    price: "250",
    url: "https://myheartbeets.com/wp-content/uploads/2015/06/mattar-paneer.jpg",
  },
  {
    name: "Dal Makhani",
    description: "Something",
    id: "f14",
    category: "dinner",
    price: "250",
    url: "https://www.funfoodfrolic.com/wp-content/uploads/2023/04/Dal-Makhani-Blog.jpg",
  },
  {
    name: "Chana Masala",
    description: "Something",
    id: "f15",
    category: "dinner",
    price: "230",
    url: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/chana-masala-recipe.jpg",
  },
  {
    name: "Pulao",
    description: "Something",
    id: "f16",
    category: "dinner",
    price: "180",
    url: "https://www.funfoodfrolic.com/wp-content/uploads/2022/05/Veg-Pulao-Blog.jpg",
  },
  {
    name: "Veg Kurma",
    description: "Something",
    id: "f17",
    category: "dinner",
    price: "250",
    url: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/veg-kurma-vegetable-korma-recipe-500x375.jpg",
  },
];
